<a href="https://colab.research.google.com/github/a4-adityaa/Data-Science-Fundamentals/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas**
Pandas is an open-source Python library used for data manipulation and analysis, specifically designed to handle structured, tabular data efficiently.


**Importing Pandas**


We can import pandas by using keyword `import pandas as pd`

In [11]:
import pandas as pd

# Series
A pandas 1-Dimensional labled array that can hold any data type...

Think of it like a single column in a spredsheet (1-Dimensional)

In [12]:
data = [100,50,75,63,88]
series = pd.Series(data, index=["a", "b","c","d","e"])
series

a    100
b     50
c     75
d     63
e     88
dtype: int64

We can use `loc[]` for accesing value using lable and `iloc[]` for accesing value using index as other programming language...

In [13]:
# we can access the single value of a list using .loc[]
print(series.loc["a"])

100

In [14]:
#Series is also mutable
series.loc["c"] = 200
series

a    100
b     50
c    200
d     63
e     88
dtype: int64

In [15]:
# Access using Index
print(series.iloc[2])

200

# Filtering
We can also filter data using operators

In [17]:
# greater than 100
print(series[series >= 100])

a    100
c    200
dtype: int64

Let's try with some dictionay....

In [19]:
calories ={"Day 1": 1750, "Day 2": 2100, "Day 3": 1700}
# The key value will be auto recognized as label and we don't explicitly need to assign label
series= pd.Series(calories)
series

Day 1    1750
Day 2    2100
Day 3    1700
dtype: int64

In [20]:
# we can aslo access the values with the help of key as Python dictionary...
series.loc["Day 3"] += 500
series

Day 1    1750
Day 2    2100
Day 3    2200
dtype: int64

In [21]:
# filtering
print(series[series > 2000])

Day 2    2100
Day 3    2200
dtype: int64

# **DataFrame**
A tabular data structure with rows and columns. (2-Dimensional).... similar to an excel spreadsheet.

In [25]:
data = {"Name": ["Aditya","Ram","Ankit"],
        "Age":[30,35,50]}
df = pd.DataFrame(data)
df

     Name  Age
0  Aditya   30
1     Ram   35
2   Ankit   50

In [28]:
df = pd.DataFrame(data, index=["Employee 1","Employee 2","Employee 3"])
# we can aslo access data using `loc[]` keyword

print(df.loc["Employee 2"])
print(df.loc[["Employee 1"]])

Name    Ram
Age      35
Name: Employee 2, dtype: object
              Name  Age
Employee 1  Aditya   30

# Adding a new Column
For adding a new column the number of rows sholud be equal

In [29]:
df["Job"] = ["cook","N/A","Cashier"]
df

              Name  Age      Job
Employee 1  Aditya   30     cook
Employee 2     Ram   35      N/A
Employee 3   Ankit   50  Cashier

# Adding a new row
For adding a new row we pass a list of dictionary into DataFrame

In [37]:
new_row= pd.DataFrame([{"Name": "Prince", "Age": 23, "Job":"Engineer"}], index=["Employee 4"])
df = pd.concat([df, new_row])
df

              Name  Age       Job
Employee 1  Aditya   30      cook
Employee 2     Ram   35       N/A
Employee 3   Ankit   50   Cashier
Employee 4  Prince   23  Engineer

# **Importing**
Let's import some csv or json file tp work with....

In [43]:
df = pd.read_csv("data.csv")
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

Selection by column

In [47]:
df["Name"]
# print all without truncating we can use `.to_string()`
# df["Name"].to_string()

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
145       Moltres
146       Dratini
147     Dragonair
148     Dragonite
149        Mewtwo
Name: Name, Length: 150, dtype: object