<a href="https://colab.research.google.com/github/a4-adityaa/Data-Science-Fundamentals/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas**
Pandas is an open-source Python library used for data manipulation and analysis, specifically designed to handle structured, tabular data efficiently.


**Importing Pandas**


We can import pandas by using keyword `import pandas as pd`

In [11]:
import pandas as pd

# Series
A pandas 1-Dimensional labled array that can hold any data type...

Think of it like a single column in a spredsheet (1-Dimensional)

In [12]:
data = [100,50,75,63,88]
series = pd.Series(data, index=["a", "b","c","d","e"])
series

a    100
b     50
c     75
d     63
e     88
dtype: int64

We can use `loc[]` for accesing value using lable and `iloc[]` for accesing value using index as other programming language...

In [13]:
# we can access the single value of a list using .loc[]
print(series.loc["a"])

100

In [14]:
#Series is also mutable
series.loc["c"] = 200
series

a    100
b     50
c    200
d     63
e     88
dtype: int64

In [15]:
# Access using Index
print(series.iloc[2])

200

# Filtering
We can also filter data using operators

In [17]:
# greater than 100
print(series[series >= 100])

a    100
c    200
dtype: int64

Let's try with some dictionay....

In [19]:
calories ={"Day 1": 1750, "Day 2": 2100, "Day 3": 1700}
# The key value will be auto recognized as label and we don't explicitly need to assign label
series= pd.Series(calories)
series

Day 1    1750
Day 2    2100
Day 3    1700
dtype: int64

In [20]:
# we can aslo access the values with the help of key as Python dictionary...
series.loc["Day 3"] += 500
series

Day 1    1750
Day 2    2100
Day 3    2200
dtype: int64

In [21]:
# filtering
print(series[series > 2000])

Day 2    2100
Day 3    2200
dtype: int64

# **DataFrame**
A tabular data structure with rows and columns. (2-Dimensional).... similar to an excel spreadsheet.

In [25]:
data = {"Name": ["Aditya","Ram","Ankit"],
        "Age":[30,35,50]}
df = pd.DataFrame(data)
df

     Name  Age
0  Aditya   30
1     Ram   35
2   Ankit   50

In [28]:
df = pd.DataFrame(data, index=["Employee 1","Employee 2","Employee 3"])
# we can aslo access data using `loc[]` keyword

print(df.loc["Employee 2"])
print(df.loc[["Employee 1"]])

Name    Ram
Age      35
Name: Employee 2, dtype: object
              Name  Age
Employee 1  Aditya   30

# Adding a new Column
For adding a new column the number of rows sholud be equal

In [29]:
df["Job"] = ["cook","N/A","Cashier"]
df

              Name  Age      Job
Employee 1  Aditya   30     cook
Employee 2     Ram   35      N/A
Employee 3   Ankit   50  Cashier

# Adding a new row
For adding a new row we pass a list of dictionary into DataFrame

In [37]:
new_row= pd.DataFrame([{"Name": "Prince", "Age": 23, "Job":"Engineer"}], index=["Employee 4"])
df = pd.concat([df, new_row])
df

              Name  Age       Job
Employee 1  Aditya   30      cook
Employee 2     Ram   35       N/A
Employee 3   Ankit   50   Cashier
Employee 4  Prince   23  Engineer

# **Importing**
Let's import some csv or json file tp work with....

In [53]:
df = pd.read_csv("data.csv", index_col="Name") # converts name as label
df

             No    Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur     1    Grass  Poison     0.7     6.9          0
Ivysaur       2    Grass  Poison     1.0    13.0          0
Venusaur      3    Grass  Poison     2.0   100.0          0
Charmander    4     Fire     NaN     0.6     8.5          0
Charmeleon    5     Fire     NaN     1.1    19.0          0
...         ...      ...     ...     ...     ...        ...
Moltres     146     Fire  Flying     2.0    60.0          1
Dratini     147   Dragon     NaN     1.8     3.3          0
Dragonair   148   Dragon     NaN     4.0    16.5          0
Dragonite   149   Dragon  Flying     2.2   210.0          0
Mewtwo      150  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

Selection by column

In [55]:
# df["Name"]  -> gives column Name
# print all without truncating we can use `.to_string()`
# df["Name"].to_string()

df[["Height","Weight"]]

            Height  Weight
Name
Bulbasaur      0.7     6.9
Ivysaur        1.0    13.0
Venusaur       2.0   100.0
Charmander     0.6     8.5
Charmeleon     1.1    19.0
...            ...     ...
Moltres        2.0    60.0
Dratini        1.8     3.3
Dragonair      4.0    16.5
Dragonite      2.2   210.0
Mewtwo         2.0   122.0

[150 rows x 2 columns]

Selection by rows

In [66]:
df.loc["Pikachu"]

No                 25
Type1        Electric
Type2             NaN
Height            0.4
Weight            6.0
Legendary           0
Name: Pikachu, dtype: object

In [65]:
# Returns only Height and Weight
df.loc["Pikachu",["Height","Weight"]]

Height    0.4
Weight    6.0
Name: Pikachu, dtype: object

In [67]:
# to Print a range
df.loc["Moltres":"Mewtwo"]

            No    Type1   Type2  Height  Weight  Legendary
Name
Moltres    146     Fire  Flying     2.0    60.0          1
Dratini    147   Dragon     NaN     1.8     3.3          0
Dragonair  148   Dragon     NaN     4.0    16.5          0
Dragonite  149   Dragon  Flying     2.2   210.0          0
Mewtwo     150  Psychic     NaN     2.0   122.0          1

In [69]:
# we can also get through `.iloc[]`
df.iloc[0:11:2] # 2 is step

            No  Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur    1  Grass  Poison     0.7     6.9          0
Venusaur     3  Grass  Poison     2.0   100.0          0
Charmeleon   5   Fire     NaN     1.1    19.0          0
Squirtle     7  Water     NaN     0.5     9.0          0
Blastoise    9  Water     NaN     1.6    85.5          0
Metapod     11    Bug     NaN     0.7     9.9          0

In [70]:
df.iloc[0:10:2, 0:3] #-> range of column

            No  Type1   Type2
Name
Bulbasaur    1  Grass  Poison
Venusaur     3  Grass  Poison
Charmeleon   5   Fire     NaN
Squirtle     7  Water     NaN
Blastoise    9  Water     NaN

Let's Search for a pokemon

In [71]:
Pokemon = input("Input a Pokemon name: ")

try:
  print(df.loc[Pokemon])
except:
  print(f"{Pokemon} not found")

Input a Pokemon name: Pikachu
No                 25
Type1        Electric
Type2             NaN
Height            0.4
Weight            6.0
Legendary           0
Name: Pikachu, dtype: object

# **Filtering**
..Keeping the rows that match a column

In [72]:
tall_pokemon = df[df["Height"] >= 2]
tall_pokemon

             No    Type1    Type2  Height  Weight  Legendary
Name
Venusaur      3    Grass   Poison     2.0   100.0          0
Ekans        23   Poison      NaN     2.0     6.9          0
Arbok        24   Poison      NaN     3.5    65.0          0
Onix         95     Rock   Ground     8.8   210.0          0
Exeggutor   103    Grass  Psychic     2.0   120.0          0
Kangaskhan  115   Normal      NaN     2.2    80.0          0
Gyarados    130    Water   Flying     6.5   235.0          0
Lapras      131    Water      Ice     2.5   220.0          0
Snorlax     143   Normal      NaN     2.1   460.0          0
Moltres     146     Fire   Flying     2.0    60.0          1
Dragonair   148   Dragon      NaN     4.0    16.5          0
Dragonite   149   Dragon   Flying     2.2   210.0          0
Mewtwo      150  Psychic      NaN     2.0   122.0          1

# **Aggregate Functions**
* Reduce the set of values into a sibgle summary value.

* Used to summarize and analyse data

* Often used with the `groupby()` function

In [73]:
# mean aggregate
df.mean(numeric_only=True) # mean only works with numeric value

No           75.500000
Height        1.200000
Weight       46.231333
Legendary     0.026667
dtype: float64

In [74]:
# sum
df.sum(numeric_only=True)

No           11325.0
Height         180.0
Weight        6934.7
Legendary        4.0
dtype: float64

In [75]:
# min
df.min(numeric_only=True)

No           1.0
Height       0.2
Weight       0.1
Legendary    0.0
dtype: float64

In [77]:
# max
df.max(numeric_only=True)

No           150.0
Height         8.8
Weight       460.0
Legendary      1.0
dtype: float64